radio_programs_compile_execute:
  default: True
  help: Enable or disable gnu radio program compilation and execution. Disable it,
    if GNU-Radio runs on a separate machine.

radio_programs_path:
  default: example/grc
  help: Path to the collection of radio programms (grc files)

gnu_radio_program_filename:
  default: ieee80211_wifi_loopback_w_fr_channel
  help: A string pointing to a function that is inside one or multiple modules. The
    function will be imported and executed without any arguments. It must return a
    tuple of inputs and targets.

gnu_radio_program:
  default: wifi_loopback
  help: A string pointing to a function that is inside one or multiple modules. The
    function will be imported and executed without any arguments. It must return a
    tuple of inputs and targets.

scenario:
  default: ieee80211codemodscenario.ieee80211_scenario
  help: A string pointing to a function that is inside one or multiple modules. The
    function will be imported and executed without any arguments. It must return a
    tuple of inputs and targets.

rpcport:
  default: 8080
  help:
rpchost:
  default: "localhost"
  help:

eventbased:
  default: False
  help:

stepTime:
  default: 1
  help:

simulate:
  default: True
  help: Enable or disable the simulation methode

simTime:
  default: 0.5
  help:

simSteps:
  default: 10
  help: Number of steps with the same Observation. The simulation changes after
    simCount steps

simDistMin:
  default: 0
  help: Minimum simulated distance in dB 

simDistMax:
  default: 20
  help: Maximum simulated distance in dB

maxRewardLoss:
  default: 30
  help: Maximum numper of steps with reward == 0 in a row
  
sync_length:
  default:
  help:
frequency:
  default:
  help:
bandwidth:
  default:
  help:
windows_size:
  default:
  help:
model: "fading_model"
N:
  default: 8
  help: the number of sinusoids to use in simulating the channel
fDTs:
  default: 50
  help: normalized maximum Doppler frequency
LOS:
  default: LOS
  help: include Line-of-Site path? selects between Rayleigh (NLOS) and Rician (LOS) models
K:
  default:
  help: Rician factor
seed:
  default: 23
  help: noise generators

