/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(moving_average_vect.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7196a75c0edecc33d5e11471d562526f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/gnugym/moving_average_vect.h>
// pydoc.h is automatically generated in the build directory
#include <moving_average_vect_pydoc.h>

void bind_moving_average_vect(py::module& m)
{

    using moving_average_vect    = gr::gnugym::moving_average_vect;


    py::class_<moving_average_vect, gr::block, gr::basic_block,
        std::shared_ptr<moving_average_vect>>(m, "moving_average_vect", D(moving_average_vect))

        .def(py::init(&moving_average_vect::make),
           D(moving_average_vect,make)
        )
        



        ;




}








