/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(rssi_cb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e3deeefacc7e62e529d179ec59a82c7b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/gnugym/rssi_cb.h>
// pydoc.h is automatically generated in the build directory
#include <rssi_cb_pydoc.h>

void bind_rssi_cb(py::module& m)
{

    using rssi_cb    = gr::gnugym::rssi_cb;


    py::class_<rssi_cb, gr::block, gr::basic_block,
        std::shared_ptr<rssi_cb>>(m, "rssi_cb", D(rssi_cb))

        .def(py::init(&rssi_cb::make),
           D(rssi_cb,make)
        )
        



        ;




}








