/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(snr_cb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(2446f0b356b95ededaf9913c74866736)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/gnugym/snr_cb.h>
// pydoc.h is automatically generated in the build directory
#include <snr_cb_pydoc.h>

void bind_snr_cb(py::module& m)
{

    using snr_cb    = gr::gnugym::snr_cb;


    py::class_<snr_cb, gr::block, gr::basic_block,
        std::shared_ptr<snr_cb>>(m, "snr_cb", D(snr_cb))

        .def(py::init(&snr_cb::make),
           D(snr_cb,make)
        )
        



        ;




}








