/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(snrdebug_ff.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d41b0aa64d038edd94d0667e6a5f87c6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/gnugym/snrdebug_ff.h>
// pydoc.h is automatically generated in the build directory
#include <snrdebug_ff_pydoc.h>

void bind_snrdebug_ff(py::module& m)
{

    using snrdebug_ff    = gr::gnugym::snrdebug_ff;


    py::class_<snrdebug_ff, gr::block, gr::basic_block,
        std::shared_ptr<snrdebug_ff>>(m, "snrdebug_ff", D(snrdebug_ff))

        .def(py::init(&snrdebug_ff::make),
           D(snrdebug_ff,make)
        )
        



        ;




}








