/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(gnugym_snr_cb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d930e70495011579c07d3e490e77d4d3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/gnugym/gnugym_snr_cb.h>
// pydoc.h is automatically generated in the build directory
#include <gnugym_snr_cb_pydoc.h>

void bind_gnugym_snr_cb(py::module& m)
{

    using gnugym_snr_cb    = gr::gnugym::gnugym_snr_cb;


    py::class_<gnugym_snr_cb, gr::block, gr::basic_block,
        std::shared_ptr<gnugym_snr_cb>>(m, "gnugym_snr_cb", D(gnugym_snr_cb))

        .def(py::init(&gnugym_snr_cb::make),
           D(gnugym_snr_cb,make)
        )
        



        ;
        
        
        py::enum_<::gr::gnugym::EqualizerSNR>(m,"EqualizerSNR")
        .value("LS_SNR", ::gr::gnugym::LS_SNR) // 0
        .value("LMS_SNR", ::gr::gnugym::LMS_SNR) // 1
        .value("COMB_SNR", ::gr::gnugym::COMB_SNR) // 2
        .value("STA_SNR", ::gr::gnugym::STA_SNR) // 3
        .export_values()
    ;

    py::implicitly_convertible<int, ::gr::gnugym::EqualizerSNR>();




}








